"""create_classification_and_feedback_tables

Revision ID: 860eec298150
Revises: 
Create Date: 2026-10-05 13:24:17.968077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860eec298150'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_type', sa.String(length=10), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('contamination', sa.String(length=20), nullable=False),
    sa.Column('ai_confidence', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('recommendation_confidence', sa.String(length=10), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_records_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_classification_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_records_status'), ['status'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['classification_records.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_request_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))

    op.drop_table('feedback')
    with op.batch_alter_table('classification_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_records_status'))
        batch_op.drop_index(batch_op.f('ix_classification_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_classification_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_classification_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_classification_records_category'))

    op.drop_table('classification_records')
    # ### end Alembic commands ###
