"""EcoSort AI - Anonymous Session History Endpoints (Stage 5).

Provides safe session-scoped history retrieval for client-side dashboards.
PRIVACY POLICY: Requires an explicit anonymous session_id. Never exposes cross-session
records or global classification history to arbitrary public callers.
"""

from typing import Optional
from fastapi import APIRouter, Depends, Header, Query
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.schemas.history import HistoryResponse
from app.services.audit_service import AuditService

router = APIRouter()


@router.get(
    "",
    response_model=HistoryResponse,
    summary="Get recent classification history for an anonymous session",
    description=(
        "Retrieves past classification summaries for the specified session_id. "
        "Supplied via query parameter (?session_id=...) or X-Session-ID header. "
        "Returns an empty list if no session_id is provided."
    ),
)
def get_session_history(
    session_id: Optional[str] = Query(
        None,
        description="Anonymous session identifier generated by the client application",
    ),
    x_session_id: Optional[str] = Header(
        None,
        alias="X-Session-ID",
        description="Optional session header alternative",
    ),
    limit: int = Query(20, ge=1, le=100, description="Number of records to retrieve"),
    offset: int = Query(0, ge=0, description="Offset for pagination"),
    db: Session = Depends(get_db),
) -> HistoryResponse:
    """Retrieves session-isolated past classifications."""
    effective_session_id = session_id or x_session_id
    if not effective_session_id:
        return HistoryResponse(
            session_id=None,
            total=0,
            items=[],
        )

    service = AuditService(db)
    return service.get_session_history(effective_session_id.strip(), limit=limit, offset=offset)
